# app/config/security.yml

security:
  provider:     main
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    App\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:  App\Entity\User
        property: username
#    in_memory:
#      memory:
#        users:
#          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      provider: main
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: affichage
      logout:
        path:       logout
        target:     login

  access_control:
  - { path: ^/TestDoctrine/add, roles: ROLE_USER}
  - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
